// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOB43bpoL2iaUak_1tQS8LiKIpARkhmk',
    appId: '1:337353990532:web:e191e2e2dfc90b5889bdd1',
    messagingSenderId: '337353990532',
    projectId: 'ida-conference-app',
    authDomain: 'ida-conference-app.firebaseapp.com',
    storageBucket: 'ida-conference-app.firebasestorage.app',
    measurementId: 'G-YZEH2M3382',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoWdicvJCdmuIsml7u6L91R8aqqfpKAM',
    appId: '1:337353990532:android:ba4bc0bdb264288e89bdd1',
    messagingSenderId: '337353990532',
    projectId: 'ida-conference-app',
    storageBucket: 'ida-conference-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSIpcqTlwMkpOc4yqprDD3p6xD6go-4Y',
    appId: '1:337353990532:ios:3137efd0cfd70c9489bdd1',
    messagingSenderId: '337353990532',
    projectId: 'ida-conference-app',
    storageBucket: 'ida-conference-app.firebasestorage.app',
    iosBundleId: 'com.example.idaConferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSIpcqTlwMkpOc4yqprDD3p6xD6go-4Y',
    appId: '1:337353990532:ios:3137efd0cfd70c9489bdd1',
    messagingSenderId: '337353990532',
    projectId: 'ida-conference-app',
    storageBucket: 'ida-conference-app.firebasestorage.app',
    iosBundleId: 'com.example.idaConferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOB43bpoL2iaUak_1tQS8LiKIpARkhmk',
    appId: '1:337353990532:web:66b93aed4c75419a89bdd1',
    messagingSenderId: '337353990532',
    projectId: 'ida-conference-app',
    authDomain: 'ida-conference-app.firebaseapp.com',
    storageBucket: 'ida-conference-app.firebasestorage.app',
    measurementId: 'G-70R52427P2',
  );
}
